service: starwars-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    TABLE_NAME: FusionadosCache
    WEATHER_API_KEY: c82fdda4ada042b8a79145454252103

  iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:PutItem
              - "dynamodb:GetItem"
              - "dynamodb:Query"
            Resource: 
              - arn:aws:dynamodb:us-east-1:993939397323:table/FusionadosCache
              - arn:aws:dynamodb:us-east-1:993939397323:table/User

functions:

  register:
    handler: dist/src/handlers/registerHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  login:
    handler: dist/src/handlers/loginHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  getFusionados:
    handler: dist/src/handlers/fusionadosHandler.getFusionados
    events:
      - http:
          path: fusionados
          method: get
          cors: true  # Habilita CORS
  
  storeData:
    handler: dist/src/handlers/almacenarHandler.storeData
    events:
      - http:
          path: almacenar
          method: post
          cors: true  # Habilita CORS
  
  getHistory:
    handler: dist/src/handlers/historialHandler.getHistory
    events:
      - http:
          path: historial
          method: get
          cors: true  # Habilita CORS
  
  apiDocs:
    handler: dist/src/handlers/swaggerJsonHandler.getSwaggerJson
    events:
      - http:
          path: api-docs
          method: get
  
resources:
  Resources:
    FusionadosCache:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FusionadosCache
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    User:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: Starwars API
    